"""Initial migration

Revision ID: 1dd45a7ccd34
Revises: 
Create Date: 2025-03-05 13:32:38.335685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dd45a7ccd34'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('UserID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Name', sa.String(length=255), nullable=False),
    sa.Column('Email', sa.String(length=255), nullable=False),
    sa.Column('PasswordHash', sa.String(length=255), nullable=False),
    sa.Column('Role', sa.Enum('Client', 'Evaluator', 'Admin'), nullable=False),
    sa.Column('CreatedAt', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('UserID'),
    sa.UniqueConstraint('Email')
    )
    op.create_table('Evaluations',
    sa.Column('EvaluationID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ClientID', sa.Integer(), nullable=False),
    sa.Column('EvaluatorID', sa.Integer(), nullable=True),
    sa.Column('Status', sa.Enum('Pending', 'In Progress', 'Completed'), server_default='Pending', nullable=True),
    sa.Column('Score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('Comments', sa.Text(), nullable=True),
    sa.Column('CreatedAt', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['ClientID'], ['Users.UserID'], ),
    sa.ForeignKeyConstraint(['EvaluatorID'], ['Users.UserID'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('EvaluationID')
    )
    op.create_table('Payments',
    sa.Column('PaymentID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ClientID', sa.Integer(), nullable=False),
    sa.Column('Amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('Status', sa.Enum('Pending', 'Completed', 'Failed'), server_default='Pending', nullable=True),
    sa.Column('PaidAt', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['ClientID'], ['Users.UserID'], ),
    sa.PrimaryKeyConstraint('PaymentID')
    )
    op.create_table('EvaluationForms',
    sa.Column('FormID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('EvaluationID', sa.Integer(), nullable=True),
    sa.Column('Location', sa.String(length=255), nullable=False),
    sa.Column('EvaluationDate', sa.Date(), nullable=False),
    sa.Column('contractor_license', sa.Boolean(), nullable=False),
    sa.Column('contractor_license_remarks', sa.Text(), nullable=True),
    sa.Column('design_compliance', sa.Boolean(), nullable=False),
    sa.Column('design_compliance_remarks', sa.Text(), nullable=True),
    sa.Column('documentation', sa.Boolean(), nullable=False),
    sa.Column('documentation_remarks', sa.Text(), nullable=True),
    sa.Column('testing_records', sa.Boolean(), nullable=False),
    sa.Column('testing_records_remarks', sa.Text(), nullable=True),
    sa.Column('wiring_regulations', sa.Boolean(), nullable=False),
    sa.Column('wiring_regulations_remarks', sa.Text(), nullable=True),
    sa.Column('circuit_breakers', sa.Boolean(), nullable=False),
    sa.Column('circuit_breakers_remarks', sa.Text(), nullable=True),
    sa.Column('earthing_bonding', sa.Boolean(), nullable=False),
    sa.Column('earthing_bonding_remarks', sa.Text(), nullable=True),
    sa.Column('exposed_wires', sa.Boolean(), nullable=False),
    sa.Column('exposed_wires_remarks', sa.Text(), nullable=True),
    sa.Column('rcd_installed', sa.Boolean(), nullable=False),
    sa.Column('rcd_installed_remarks', sa.Text(), nullable=True),
    sa.Column('panel_labeling', sa.Boolean(), nullable=False),
    sa.Column('panel_labeling_remarks', sa.Text(), nullable=True),
    sa.Column('equipment_inspection', sa.Boolean(), nullable=False),
    sa.Column('equipment_inspection_remarks', sa.Text(), nullable=True),
    sa.Column('safety_signage', sa.Boolean(), nullable=False),
    sa.Column('safety_signage_remarks', sa.Text(), nullable=True),
    sa.Column('emergency_switches', sa.Boolean(), nullable=False),
    sa.Column('emergency_switches_remarks', sa.Text(), nullable=True),
    sa.Column('circuit_loading', sa.Boolean(), nullable=False),
    sa.Column('circuit_loading_remarks', sa.Text(), nullable=True),
    sa.Column('safety_procedures', sa.Boolean(), nullable=False),
    sa.Column('safety_procedures_remarks', sa.Text(), nullable=True),
    sa.Column('overall_rating', sa.Enum('Excellent', 'Satisfactory', 'Needs Improvement', 'Non-Compliant'), nullable=False),
    sa.Column('corrective_actions', sa.Text(), nullable=True),
    sa.Column('additional_comments', sa.Text(), nullable=True),
    sa.Column('evaluator_signature', sa.String(length=255), nullable=False),
    sa.Column('signed_date', sa.Date(), nullable=False),
    sa.Column('CreatedAt', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('UpdatedAt', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['EvaluationID'], ['Evaluations.EvaluationID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('FormID'),
    sa.UniqueConstraint('EvaluationID')
    )
    op.create_table('Reports',
    sa.Column('ReportID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('EvaluationID', sa.Integer(), nullable=True),
    sa.Column('ReportFilePath', sa.String(length=255), nullable=False),
    sa.Column('GeneratedAt', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['EvaluationID'], ['Evaluations.EvaluationID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ReportID'),
    sa.UniqueConstraint('EvaluationID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Reports')
    op.drop_table('EvaluationForms')
    op.drop_table('Payments')
    op.drop_table('Evaluations')
    op.drop_table('Users')
    # ### end Alembic commands ###
